
name: Synchronizing Algolia Search

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}

    steps:
    - uses: actions/checkout@v2
    - name: Deleting existing indexes object
      shell: bash
      run: |
        curl -X POST -H "X-Algolia-API-Key: $ALGOLIA_API_KEY" -H "X-Algolia-Application-Id: $ALGOLIA_APPLICATION_ID" "https://$ALGOLIA_APPLICATION_ID.algolia.net/1/indexes/test-index/clear"
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Installing dependency
      run: npm install
    - name: Synchronizing search engine
      shell: bash
      run: ALGOLIA_APP_ID=$ALGOLIA_APPLICATION_ID ALGOLIA_ADMIN_KEY=$ALGOLIA_API_KEY node search-engine-sync.js